language: generic
dist: trusty
services: docker
sudo: false
matrix:
  include:
    - name: x86_64-linux
    # HiKey970 using CPU: ARM Cortex-A73 (ARMv8-A 64-bit)
    # https://www.96boards.org/documentation/consumer/hikey/hikey970/
    # https://github.com/multiarch/qemu-user-static
    # https://hub.docker.com/r/multiarch/ubuntu-debootstrap/tags/
    - name: aarch64-linux
      sudo: required
      env:
        - ARCH=arm64
      install:
        # Prepare QEMU.
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        # Build container image.
        - |
          docker build --rm -f Dockerfile-${ARCH} -t gogut .
      script:
        - docker run --rm -t gogut ./sample_test.sh
  allow_failures:
  fast_finish: true
before_script:
  # Show environment.
  - uname -a
  - id
  - pwd
script:
  - ./sample_test.sh
